
server:
  port: 8082
  servlet:
    context-path: /api

spring:
  database: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:


  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect

  logging:
    level:

      org-springframework.web: DEBUG
      ma.pfe: DEBUG